FileVersion = 1
Dependencies = {corlib = "*", AStar-beef = "*"}

[Project]
Name = "example"
TargetType = "BeefGUIApplication"
StartupObject = "example.Program"

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\..\\libs\\x86_64-windows-msvc\\astar_d.lib"]

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\..\\libs\\x86_64-windows-msvc\\astar_d.lib"]