FileVersion = 1

[Project]
Name = "AStar-beef"
DefaultNamespace = "AStar"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\astar_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\astar.lib"]